#Filename: <OrangeMoon.py>
#Programmer: Maheen A. Qureshi

#importing breaks between text
import time

#Pre-defining options for the user
yesorno = ["yes", "no"]
options = ["a", "b", "c"]

#Final function used in the game. Asks end user if they will play again.
def playgame_again():
     print ("")
     answer = ""
     while answer not in yesorno:
          answer = input ("Do you wish to embark on this quest again? ")
          if answer == "no":
               print ("")
               time.sleep (5)
               #Ending Credits
               print ("")
               print ("PROGRAMMED BY MAHEEN A. QURESHI, 2020")
               print ("")
               time.sleep (2)
               print ("TYFUMP-Thank you for using my program.")
          elif answer == "yes":
               print ("")
               print ("'Let us begin once more...'")
               time.sleep (3)
               gameIntro()
          else:
               print ("")
               print ("I didn't understand.")


#GAME OUTRO
def pianomanReprise():
     print ("You open your eyes, and find yourself once again back in the Piano Man Inn.")
     print ("The sound of piano music fills your ears, and you look around and notice")
     print ("something strange...")
     print ("")
     time.sleep (5)
     print ("All the eyes in the room are on you. The >Piano Man< stops playing and walks ")
     print ("over to the chest, and guestures for you to come forward.")
     time.sleep (4)
     print ("You pull out the five keys, and stick them one by one into the chest.")
     print ("")
     print ("Everyone in the room cheers, as you open the chest and pull out a glowing orange ")
     print ("moon charm.")
     print ("")
     print ("You look in the crowd, and see the >Tiger<, >Rabbit Mask<, >The Agents< (turns out they")
     print ("became good guys after they failed the >Pirate King<) and of course, the >Piano Man<.")
     time.sleep (8)
     print ("")
     print ("Once together, the five machine parts together look like a large disk.")
     print ("")
     print ("'Stand on the disk, and close your eyes... you'll be able to go home with it!")
     print ("Closing your eyes, you stand on the disk, and close your eyes.")
     print ("")
     time.sleep (4)
     print ("Opening them again, you see you are back in your house. 'OUT OF BED! ITS 1:00 PM ALREADY!")
     print ("you hear. Blinking in confusion, you think, 'Was it all just a dream?'")
     time.sleep (4)
     print ("")
     print ("You look over and see a strange charm sitting on your dresser. It's an Orange Moon.")
     print ("")
     print ("So... it was real...")
     print ("Wishing that you'd been able to keep the sword, you get out of bed to brush your teeth.")
     print ("")
     time.sleep (4)
     print ("THE END OF ORANGE MOOON.")
     playgame_again()
          
#SIXTH LEVEL IN GAME
def orangemoonLvlSix():
     print ("")
     print ("FINAL LEVEL: ORANGE MOON")
     print ("")
     time.sleep (3)
     print ("The moon is full, and so bright now, that it leaves an orange glow on your ")
     print ("skin. You stand at an ocean, with a lonely dock ahead. The hairs on your neck are on end.")
     print ("")
     time.sleep (4)
     print ("Below is a map of this level.")
     #MAP OF LEVEL
     print ("|‾‾‾‾‾‾‾‾‾‾‾|‾|‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾|")
     print ("|           |D|                 |")
     print ("|           |O|                 |")
     print ("|           |C|                 |")
     print ("|           |K|                 |")
     print ("|   |‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾|      |")
     print ("|   |     ???X???        |      |")
     print ("|___|____________________|______|")
     time.sleep (10)
     print ("Opening your bag, you take note of your items.")
     print ("")
     print ("ITEMS:")
     print ("")
     print (">Time Watch<")
     print (">Walkie Talkie<")
     print (">Sword<")
     print (">Compass<")
     print (">4/5 Keys<")
     time.sleep (6)
     print ("")
     print ("Taking a deep breath, you walk down the dock.")
     print ("")
     time.sleep (2)
     #Start of final Boss Battle
     print ("A ship rises from within the water, and you get splashed. It's salty and cold.")
     print ("'WHO CHALLENGES THE >Pirate King< ?")
     print ("")
     print ("YOU HAVE ENCOUNTERED AN ENEMY! >Pirate King<")
     print ("")
     time.sleep (4)
     print ("Staggering and stuttering, you say 'M-M-ME!")
     print ("'Well, M-m-me, shall we duel?")
     print ("")
     print ("")
     time.sleep (4)
     print ("Raising your >Sword<, you charge at the >Pirate King<, but he easily dodges.")
     print ("'NICE TRY, BUT YOU'RE WEAK!")
     print ("")
     print ("This won't work... you need a new tactic to defeat him!")
     decisionlast = ""
     while decisionlast not in options:
          print ("")
          decisionlast = input("Do you try a sneak attack or do you continue attacking head on? ")
          if decisionlast == "a":
               print ("")
               print ("You decide to try a sneak attack, since it's too dangerous straightforwards.")
               print ("")
               time.sleep (3)
               print (">Sword< in hand, you swim around to the back of the ship and climb on. ")
               print ("'YOU CAN'T HIDE FROM ME!' yells the >Pirate King<. You take a step forwards, and slash")
               print ("the back of his leg, going back into hiding behind some barrels.")
               print ("")
               time.sleep (6)
               print ("The >Pirate King< howls in rage, and turns around, spotting you. He swipes the >Sword< from ")
               print ("your hand, with it landing into the ocean. Which item do you pull out now to save you?")
               print ("")
               itemlast = ""
               while itemlast not in options:
                    itemlast = input ("a) Time Watch  b) Walkie Talkie  c) Compass ")
                    if itemlast == "a":
                         print ("")
                         print ("You pull out the >Time Watch<, desperately pressing its button.")
                         print ("However, you remember that it dosen't work until you've got the key of ")
                         print ("the level... so it is pointless.")
                         time.sleep (5)
                         print ("")
                         print ("The >Pirate King< eyes the watch, and yells 'MY AGENTS DIDN'T GET THAT YET? NO WONDER!")
                         print ("THEY SHALL BE PUNISHED!' You try to creep away...but fail once again.")
                         print ("")
                         time.sleep (4)
                         print ("'WHERE ARE YOU GOING, HUH?' The >Pirate King< grabs you and throws you far into the ocean.")
                         print ("You drown.")
                         print ("")
                         time.sleep (4)
                         print ("GAME OVER.")
                         playgame_again()
                    elif itemlast == "b":
                         print ("")
                         print ("You grab the >Walkie Talkie< and yell 'HELP!' in it. You hear an 'okay.' back, along ")
                         print ("with lots of static... The >Pirate King< pulls back his arm and is about to stab you, but ")
                         print ("freezes!")
                         print ("")
                         time.sleep (6)
                         print ("Looking around, you see the >Rabbit Mask< standing. The >Pirate King< falls ")
                         print ("to the ground. >Rabbit Mask< reaches down and yanks something out of the >Pirate King's<")
                         print ("pocket.")
                         print ("")
                         time.sleep (6)
                         print ("YOU GOT THE FINAL KEY! 5/5")
                         print ("")
                         time.sleep(2)
                         print ("'Thank you!' You gasp. >Rabbit Mask< simply stares.")
                         print ("")
                         print ("YOU DEFEATED THE >Pirate King<!")
                         time.sleep (4)
                         print ("Wiping a few tears you take the fifth key,")
                         print ("and press the button of the >Time Watch<.")
                         print ("")
                         time.sleep (5)
                         pianomanReprise()
                    elif itemlast == "c":
                         print ("")
                         print ("You grab the >Compass<, and look for a direction that it points in. It surprisingly points")
                         print ("right at the >Pirate King<! Without thinking, you walk straight towards him, and see an ")
                         print ("orange glint around his neck. A key?")
                         time.sleep (7)
                         print ("")
                         print ("Reaching out, you grab the key off his neck and press the button on your >Time Watch<.")
                         print ("")
                         print ("YOU GOT A KEY! (5/5)")
                         print ("")
                         time.sleep (3)
                         print ("Both of you freeze, and you stick out your tongue at the bewildered >Pirate King< before")
                         print ("dissapearing with the watch.")
                         time.sleep (4)
                         print ("")
                         print ("YOU ESCAPED THE >Pirate King<!")
                         print ("")
                         time.sleep (1)
                         print ("ENTERING OUTRO SHORTLY...")
                         print ("")
                         time.sleep (3)
                         pianomanReprise()
                    else:
                         print ("")
                         print ("I didn't understand.")
                         print ("")
          elif decisionlast == "b":
               print ("")
               print ("You decide to attack the >Pirate King< head on once more, but he swipes the >Sword< out of your ")
               print ("hand. 'YOU CAN'T FIGHT ME! GIVE UP!' He grabs you by the hair and throws you into the ocean.")
               print ("")
               time.sleep (4)
               print ("GAME OVER.")
               print ("")
               playgame_again()
          else:
               print ("")
               print ("I didn't understand that.  ")
               print ("")
     
     
#FIFTH LEVEL IN GAME
def gibbousLvlFive():
     print ("")
     print ("LEVEL FIVE: GIBBOUS")
     print ("")
     print ("You stand at an empty train station, with no one in sight. High in the sky, a bright gibbous Orange Moon")
     print ("shines down on you. In front of you is a train with open doors, and behind you is a ticket booth.")
     print ("")
     print ("Below is a map of this level.")
     #MAP OF LEVEL
     print ("|‾‾‾‾‾‾‾‾‾|‾‾‾‾‾X‾‾‾‾‾‾‾|‾‾‾‾‾‾|")
     print ("|         |TRAIN STATION|---|  |")
     print ("|          ‾‾‾‾‾‾‾‾‾‾‾‾‾    |  |")
     print ("|              _____________|  |")
     print ("|              |               |")
     print ("|       |‾‾‾‾‾‾|‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾|")
     print ("|       |ARCADE| AMUSEMENT PARK|")
     print ("|_______|__X___|__________X____|")
     time.sleep (10)
     gibbousplace = ""
     while gibbousplace not in options:
          gibbousplace = input ("Which do you wish to go to? a) ticket booth or b) train ? ")
          if gibbousplace == "a":
               print ("")
               print ("You go to the ticket booth and peer in. It seems empty.")
               print ("Suddenly a man in a rabbit mask springs up from inside, and wordlessly hands you two tickets.")
               print ("")
               time.sleep (4)
               print ("YOU MET >Rabbit Mask<. CLASS >Unknown<")
               print ("")
               time.sleep (1)
               print ("...shocking. He waves, and then... disappears? Where did he go?")
               print ("Still confused, you look down at the tickets. One is for a train, and another is for...")
               print ("an amusement park? You head into the train, wondering what is going on.")
               time.sleep (8)
          elif gibbousplace == "b":
               print("")
               print ("You sit down in the train, and peer out its windows. There doesn't seem to be anyone else around.")
               print ("Turning around, you jump! A man in a rabbit mask sits next to you, staring.")
               print ("")
               time.sleep (4)
               print ("YOU MET >Rabbit Mask<. CLASS >Unknown<")
               print ("")
               time.sleep (1)
               print ("The train starts moving, and you uncomfortably stand up and look for another seat.")
               print ("")
               print ("Your >Walkie Talkie< sputters to life, and you hear 'Have you found the target yet?' ")
               print ("'No sir, not yet.' 'That watch is important, we must not lose it! FIND THEM!'")
               print ("")
               time.sleep (5)
               print ("Could this be... >The Agents< ??? They're still looking for you! ")
               print ("")
               print ("Turning down the volume of the >Walkie Talkie<, you look back at the person in the >Rabbit Mask<.")
               print ("who still sits and stares. The train finally stops and opens its doors.")
               print ("")
               time.sleep (6)
               print ("'ARRIVED AT >The Amusement Park< DOORS WILL OPEN ON YOUR LEFT.' Says a cool female voice ")
               print ("from the speakers. Wanting to get away from the >Rabbit Mask<, you run out and ")
               print ("head into a large amusement park. There are two areas in it. The rides and the arcade.")
               print ("")
               rideorarcade = ""
               while rideorarcade not in options:
                    rideorarcade = input ("Which do you go in? a) rides or b) arcade ? ")
                    if rideorarcade == "a":
                         print ("")
                         print ("You want to go to the rides! Roller Coasters are great! But you are unsure ")
                         print ("as to which one to go to. Pulling out your >Compass< you see it pointing at ")
                         print ("the largest roller coaster in the park.")
                         print ("")
                         time.sleep (6.5)
                         print ("Time to ride it. You go and sit down on the frontmost seat, and try pulling ")
                         print ("on the seatbelt, but fail. Suddenly, an attendant comes from behind and puts ")
                         print ("your seatbelt on for you. Looking up, you realize...")
                         print ("")
                         time.sleep (6.5)
                         print ("They wear a >Rabbit Mask<. It's the person from the train station! Opening your mouth,")
                         print ("words fail you and the ride speeds up, leaving >Rabbit Mask< behind.")
                         print ("")
                         print ("After a scary and wild roller coaster ride, you gasp for air, trying to climb out.")
                         print ("Once again, the >Rabbit Mask< helps you out of your seat. Before you run from them,")
                         print ("terrified, they hand you an orange key, and say 'Good Luck.', pressing the button on ")
                         print ("your watch for you. Still shocked, you're zapped away from the world of GIBBOUS.")
                         time.sleep (10)
                         print ("YOU MADE AN ALLY! >Rabbit Mask<")
                         time.sleep (1)
                         print ("")
                         print ("YOU GOT A KEY! 4/5")
                         print ("")
                         time.sleep (1)
                         print ("ENTERING FINAL LEVEL SHORTLY...")
                         print ("")
                         time.sleep (2)
                         orangemoonLvlSix()
                    elif rideorarcade == "b":
                         print ("")
                         print ("You prefer arcades from roller coasters, honestly. ")
                         print ("Walking into the arcade room, you see glow in the dark games all around you.")
                         print ("However, you have only one ticket. ")
                         time.sleep (6)
                         print ("Pulling out your >Compass<, you see it pointing to one of the largest games in the arcade.")
                         print ("The game is called 'ORANGE MOON', with quite a few familiar faces... you see the piano ")
                         print ("man, the agents, a tiger, the pirate king's sons, and a bigger scarier looking pirate.")
                         print ("'Now who could that be?")
                         print ("")
                         time.sleep (8)
                         print ("It's a shooting game; whichever object you shoot, you will win. Hanging above")
                         print ("the prize box is an orange key.")
                         print ("Taking careful aim, you shoot at the orange key... and miss.")
                         print ("")
                         time.sleep (6)
                         print ("'What now?!' You think. Now you'll never get home... unless you could get another ticket and ")
                         print ("play again... looking up you jump. >Rabbit Mask< stands, holding another ticket in their hand")
                         print ("")
                         print ("Reaching out and taking it, you insert it in the game and try again. This time, you hit the key and ")
                         print ("it falls out with a clang.")
                         print ("")
                         time.sleep (8)
                         print ("YOU GOT A KEY! 4/5")
                         print ("")
                         time.sleep (1)
                         print (">Rabbit Mask< reaches out and presses the button on your watch, saying 'good luck.'")
                         print ("In a confusion, you are zapped away from the world of GIBBOUS.")
                         print ("")
                         time.sleep (4)
                         print ("YOU MADE AN ALLY! >Rabbit Mask<")
                         print ("")
                         time.sleep (1)
                         print ("ENTERING THE FINAL LEVEL SHORTLY...")
                         print ("")
                         time.sleep (3)
                         orangemoonLvlSix()
                    else:
                         print ("")
                         print ("I didn't understand, please repeat.")
                         print ("")
          else:
               print ("")
               print ("I didn't understand, please repeat.")
               print ("")
               
#FOURTH LEVEL IN GAME
def halfmoonLvlFour():
     print ("")
     print ("LEVEL FOUR: HALF MOON")
     print ("")
     time.sleep (2)
     print ("Taking a deep breath, you smell salt and hear seagulls. Opening your eyes")
     print ("you see that you're standing at the head of a ship, sailing... in the clouds?")
     print ("")
     time.sleep (4)
     print ("You can see right in front of you, a half moon, which is now glowing orange.")
     print ("It almost feels as if you are sailing right to it.")
     print ("")
     time.sleep (5)
     print ("The ship smacks into a seagul, and you see it spiral down. Oops.")
     print ("Looking around, you see on the ship that there's a compass and a map.")
     print ("Here is a map of the level.")
     print ("")
     time.sleep (8)
     #MAP OF LEVEL
     print ("|‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾)‾‾‾‾‾‾‾‾‾|")
     print ("|                     (   X      |")
     print ("|  _-------_           (         |")
     print ("| -  SHIP   -           ) ISLAND |")
     print ("|  ‾‾‾‾‾‾‾‾‾           (         |")
     print ("|                       )        |")
     print ("|                        (       |")
     print ("|_________________________)______|")
     time.sleep (8)
     print ("")
     print ("YOU GOT AN ITEM! >Compass<")
     print ("Helps make decisions and find directions.")
     print ("           N     ")
     print ("      A    |  ")
     print ("      <\> )|(  ")
     print ("        \  |  (  ")
     print ("      )  \ |    (  ")
     print ("    )     \|      (")
     print ("W-)--------O--------(-(-E ") 
     print ("    )      |\     (      ")
     print ("      )    | \  (      ")
     print ("        )  |  \     ")
     print ("          )|( <\>  ")
     print ("           |      ")
     print ("           S      ")

     print ("")
     time.sleep (3)
     print ("The >Compass< points towards the east, so you steer the ship in that direction.")
     print ("Below you, now, you can see an island up ahead. But you realize that... you dont know how to land...")
     print ("")
     landing = ""
     while landing not in options:
          landing = input ("Will you try steering the ship downwards or jump out of it into the ocean? ")
          if landing == "a":
               print ("")
               print ("You attempt to steer the ship downwards, but you lose control and crash!")
               print ("Slightly sore but otherwise okay, you hear rumbling voices")
               print ("")
               time.sleep (4)
               print ("WHOOOO DAARES DISTUUURB OUR ISLANDDD?")
               print ("")
               print ("Turning in confusion, you see a group of pirates, with their swords raised.")
               print ("Why does everyone have swords today?")
               print ("")
               time.sleep (6)
               print ("YOU HAVE ENCOUNTERED AN ENEMY! >Pirate King's Sons<")
               print ("")
               time.sleep (2)
               print ("Pulling out your >Sword<, you start fighting them back.")
               piratefight = ""
               while piratefight not in options:
                    piratefight = input("Do you try 1v1-ing the strongest looking guy or try attacking all the weaker ones? ")
                    if piratefight == "a":
                         print ("")
                         print ("This world won't get the best of you! 'FIGHT ME 1V1, THEE COWARD!', you yell at the biggest guy.")
                         print ("'FINE!' he says. 'IF YOU WIN... I'LL GIVE YOU ANOTHER KEY!' Interesting, you think.")
                         print ("")
                         time.sleep (5)
                         print ("His anger seems to increase even more from this, and you start to fight with energy you")
                         print ("didn't know you posessed.")
                         time.sleep (5)
                         print ("")
                         print ("After an exhausting battle, you both lower your swords. The >Pirate King's Son< tosses")
                         print ("you another orange key, true to his word. 'THIS ISN'T OVER! OUR FATHER WILL DEFEAT")
                         print ("YOU FOR SURE!' Him and all his brothers run away into the sunset.")
                         time.sleep (8)
                         print ("")
                         print ("YOU DEFEATED >Pirate King's Sons< !")
                         time.sleep (1)
                         print ("YOU GOT A KEY! 3/5")
                         print ("")
                         time.sleep (1)
                         print ("Feeling super cool, you press your watch, smirking.")
                         print ("")
                         print ("Entering level 5 shortly...")
                         print ("")
                         time.sleep (3)
                         gibbousLvlFive()
                    elif piratefight == "b":
                         print ("")
                         print ("The biggest guy looks mad scary, so you start fighting the smaller guys.")
                         print ("However... this dosen't go so well, since they all gang up on you...")
                         print ("")
                         print ("'GET HIM!' they yell, and before you know it, you hear no more.")
                         print ("The last thing you notice before you die is an orange moon in the sky.")
                         print ("")
                         time.sleep (8)
                         print ("GAME OVER")
                         playgame_again()
                    else:
                         print ("")
                         print ("Could you repeat? ")
                         print ("")
          elif landing == "b":
               print ("")
               print ("You take a deep breath, and JUMP into the ocean.")
               print ("Soaked and bruised, you walk onto the island shore.")
               print ("")
               time.sleep (4)
               print ("Suddenly, you see a band of pirates on the island run towards you.")
               print ("'GET 'EM, BOYS!' What seems to be their leader yells. You raise your >Sword< and try to fight.")
               print ("")
               print ("YOU HAVE ENCOUNTERED AN ENEMY! >Pirate King's Sons<")
               time.sleep (5)
               print ("However, you are severely injured from the jump, and can't fight, leading to your death.")
               print ("")
               time.sleep (3)
               print ("GAME OVER.")
               playgame_again()
          else:
               print ("")
               print ("Could you repeat? ")
                    
#THIRD LEVEL IN GAME
def crescentLvlThree():
     print ("")
     print ("LEVEL THREE: CRESCENT")
     print ("")
     print ("You land on what seems to be the rooftob of a building in a busy city.")
     print ("Hung on one of the buildings is a large flag with a tiger on it, saying 'CRESCENT CITY'.")
     time.sleep (6)
     print ("")
     print ("The orange moon is now a solid crescent, still light but more clearly visible.")
     print ("")
     print ("Below is a map of this level.")
     #MAP OF LEVEL
     print ("|‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾|")
     print ("|   |‾|      |‾|       |‾| ____ |")
     print ("|    ‾   |‾|  ‾     |‾| ‾ |ROOF||")
     print ("|   |‾|   ‾          ‾     ‾‾‾‾ |")
     print ("|‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾|")
     print ("|   X  CITY PARADE              |")
     print ("|‾‾‾‾|‾|‾‾‾‾‾‾‾‾‾‾‾‾‾‾|‾|‾‾‾‾‾‾‾|")
     print ("|_______________________________|")
     time.sleep (10)
     print ("You look around, and see two things; a walkie talkie, and stairs going down.")
     print ("")
     print ("YOU GOT AN ITEM! >Walkie Talkie<")
     print ("For communicating (and eavesdropping)")
     print ("     .  ")       
     print ("\   /    ") 
     print ("-=  o  =- ")
     print ("/ | \   ") 
     print ("  |     ")
     print ("  | ")        
     print ("  |")
     print ("  |=====. ") 
     print ("  |.---.|")
     print ("  ||=o=|| ")
     print ("  ||   ||")
     print ("  ||   || ")
     print ("  ||___|| ")
     print ("  |[:::]|")
     print ("  '-----' ")

     time.sleep (5)
     print ("")
     print ("Heading downstairs, you walk straight into a parade of people wearing different clothes,")
     print ("holding up signs with a tiger on it, and some rich looking politicians giving a speech.")
     print ("")
     time.sleep (6)
     print ("Suddenly, you hear the >Walkie Talkie< come to life. '")
     print ("It's me! Are you in CRESCENT yet?")
     Crescentwalkie = ""
     while Crescentwalkie not in yesorno:
          Crescentwalkie = input ("Wait... who could this be? Do you reply? yes or no? ")
          if Crescentwalkie == "yes":
               print ("")
               print ("'Yes, I'm in CRESCENT. But who is this?', you say.")
               print ("'Oh sorry, heh it's me, the >Piano Man<! Listen, you've gotta get outta there, there's--'")
               print ("A sudden rush of static causes you to be unable to hear the rest.")
               print ("")
               time.sleep (7)
               print ("'What?!' you shout, but with the yells of the paraders, you can barely hear anything except ")
               print ("one word. 'Riot.' Hah, Riot. Riot... RIOT? Turning around, you hear screams, and see a group of ")
               print ("rebels run onto the stage, throwing aside the politicians.")
               print ("")
               print ("Then... a tiger comes running into the crowd.")
               print ("")
               time.sleep (9)
               print ("YOU HAVE COME ACROSS >The Tiger<. CLASS: UNKNOWN")
               print ("")
               time.sleep (1)
               print ("Lowkey terrified, you turn and see the >Tiger< facing you, it's intense eyes glaring into yours.")
               print ("Someone in the parade shoves a sword into your hand, and you hear cheers of FIGHT! FIGHT! FIGHT!")
               time.sleep (5)
               print ("A sword? Wait wha--")
               print ("")
               print ("YOU GOT AN ITEM! >Sword<")
               print ("Hurts if slashed by it")
               print ("         />_________________________________ ")
               print ("[########[]_________________________________> ")
               print ("         \> ")
               print ("")
               time.sleep (5)
               tigerFight = ""
               while tigerFight not in options:
                    tigerFight = input ("Do you fight the >Tiger< or reason with it? ")
                    if tigerFight == "a":
                         print ("")
                         print ("'I WILL FIGHT THE TIGER!', you yell.")
                         print ("")
                         print ("There's no turning back now. Raising the >Sword< above your head, you lunge at the tiger.")
                         print ("It howls in pain as you strike it, and claws you back with its sharp claws.")
                         time.sleep (7)
                         print ("")
                         keepFightTiger = ""
                         while keepFightTiger not in options:
                              keepFightTiger = input ("Ouch. That hurt. This isn't going so well... do you want to keep fighting or escape? ")
                              if keepFightTiger == "a":
                                   print ("")
                                   print ("Hah! I'm gonna keep fighting! You scoff")
                                   print ("One more swipe, and the >Tiger< grabs you and devours you whole. Sorry, mate.")
                                   print ("")
                                   time.sleep (4)
                                   print ("GAME OVER.")
                                   playgame_again()
                              elif keepFightTiger == "b":
                                   print ("")
                                   print ("No way bro, you aren't dying today.")
                                   print ("Suddenly, you remember, the >Time Watch<! Desperately pressing its button, >Sword< in hand,")
                                   print ("you hear no noise...")
                                   print ("")
                                   time.sleep (7)
                                   print ("YOU ESCAPED >The Tiger<!")
                                   time.sleep (1)
                                   print ("ENTERING LEVEL FOUR SHORTLY...")
                                   time.sleep (3)
                                   halfmoonLvlFour()
                              else:
                                   print ("")
                                   print ("I didn't get that, could you repeat? ")
                    elif tigerFight == "b":
                         print ("")
                         print ("'Excuse-me... Tiger sir? Uhm, actually... I don't want to hurt you...', you say, feeling foolish.")
                         print ("The >Tiger< takes one look at you, picks you up in its teeth, and starts running")
                         print ("")
                         time.sleep (6)
                         print ("Feeling your death coming towards you, you close your eyes for the final time...")
                         print ("But suddenly you aren't moving anymore. The >Tiger< puts you down, and says, ")
                         print ("'INDEED... YOU ARE NOT LIKE OTHERS. I SHALL REWARD YOU FOR SPARING ME!'")
                         print ("")
                         time.sleep (8)
                         print ("... ok this is going better than you thought.")
                         print ("The >Tiger< yanks somethiing out of its fur with its teeth (gross!")
                         print ("It's... a wet tiger-spit covered orange key!")
                         print ("")
                         print ("YOU GOT A KEY! 2/5")
                         time.sleep (6)
                         print ("'NOW GO, CHILD. GO, AND FIGHT YOUR ENEMY BEFORE THE ORANGE MOON IS FULL...'")
                         print ("The >Tiger< dissapears in a mist. Wait... enemy? There's more enemies?")
                         print ("")
                         time.sleep (4)
                         print ("You sigh, and press the >Time Watch< button.")
                         print ("")
                         print ("ENTERING LEVEL FOUR SHORTLY...")
                         time.sleep (3)
                         halfmoonLvlFour()
                    else:
                         print ("")
                         print ("I didn't get that. ")
          elif Crescentwalkie == "no":
               print ("Talking into random walkie talkies that you just found is dangerous.")
               print ("")
               print ("Shoving it into your pocket, you walk down the stairs into what seems like a large parade.")
               print ("People walk around, shouting, and some rich looking politicians stand on a stage, giving a speech and ")
               print ("throwing money in the air for people to scramble and grab.")
               print ("")
               time.sleep (8)
               print ("Suddenly, you hear screams. Turning around, you see a group of ")
               print ("rebels run onto the stage, throwing aside the politicians.")
               print ("")
               print ("Then... a tiger comes running into the crowd.")
               print ("")
               time.sleep (6)
               print ("YOU HAVE COME ACROSS >The Tiger<. CLASS: UNKNOWN")
               print ("")
               time.sleep (1)
               print ("Lowkey terrified, you turn and see the >Tiger< facing you, it's intense eyes glaring into yours.")
               print ("Someone in the parade shoves a sword into your hand, and you hear cheers of FIGHT! FIGHT! FIGHT!")
               time.sleep (5)
               print ("A sword? Wait wha--")
               print ("")
               print ("YOU GOT AN ITEM! >Sword<")
               print ("Hurts if you get slashed by it.")
               print ("")
               time.sleep (5)
               tigerfight = ""
               while tigerfight not in options:
                    tigerfight = input ("Do you fight the >Tiger< or reason with it? ")
                    if tigerfight == "a":
                         print ("")
                         print ("'I WILL FIGHT THE TIGER!', you yell.")
                         print ("")
                         print ("There's no turning back now. Raising the >Sword< above your head, you lunge at the >Tiger<.")
                         print ("It howls in pain as you strike it, and claws you back with its sharp claws.")
                         time.sleep (6)
                         print ("")
                         keepfightTiger = ""
                         while keepfightTiger not in options:
                              keepfightTiger = input ("Ouch. That hurt. This isn't going so well... do you want to keep fighting or escape? ")
                              if keepfightTiger == "a":
                                   print ("")
                                   print ("Hah! I'm gonna keep fighting! You scoff")
                                   print ("One more swipe, and the >Tiger< grabs you and devours you whole. Sorry, mate.")
                                   print ("")
                                   time.sleep (4)
                                   print ("GAME OVER.")
                                   playgame_again()
                              elif keepfightTiger == "b":
                                   print ("")
                                   print ("No way bro, you aren't dying today.")
                                   print ("Suddenly, you remember, the >Time Watch<! Desperately pressing its button, >Sword< in hand,")
                                   print ("you hear no noise...")
                                   print ("")
                                   time.sleep (6)
                                   print ("YOU ESCAPED >The Tiger<!")
                                   time.sleep (1)
                                   print ("")
                                   print ("ENTERING LEVEL FOUR SHORTLY...")
                                   time.sleep (4)
                                   halfmoonLvlFour()
                              else:
                                   print ("")
                                   print ("I didn't get that, could you repeat? ")
                    elif tigerfight == "b":
                         print ("")
                         print ("'Excuse-me... tiger sir? Uhm, actually... I don't want to hurt you...', you say, feeling foolish.")
                         print ("The >Tiger< takes one look at you, picks you up in its teeth, and starts running")
                         print ("")
                         time.sleep (6)
                         print ("Feeling your death coming towards you, you close your eyes for the final time...")
                         print ("But suddenly you aren't moving anymore. The >Tiger< puts you down, and says, ")
                         print ("'INDEED... YOU ARE NOT LIKE OTHERS. I SHALL REWARD YOU FOR SPARING ME!'")
                         print ("")
                         time.sleep (7)
                         print ("... ok this is going better than you thought.")
                         print ("The >Tiger< yanks somethiing out of its fur with its teeth (gross!")
                         print ("It's... a wet tiger-spit covered orange key!")
                         print ("")
                         print ("YOU GOT A KEY! 2/5")
                         print ("")
                         time.sleep (7)
                         print ("'NOW GO, CHILD. GO, AND FIGHT YOUR ENEMY BEFORE THE ORANGE MOON IS FULL...'")
                         print ("The >Tiger< dissapears in a mist. Wait... enemy? Which enemy?")
                         print ("")
                         time.sleep (3)
                         print ("Sighing, you press the >Time Watch< and disappear from the world of CRESCENT.")
                         print ("ENTERING LEVEL FOUR SHORTLY...")
                         time.sleep (3)
                         halfmoonLvlFour()
                    else:
                         print ("")
                         print ("I didn't get that. " )
          else:
               print ("")
               print ("Could you repeat that please? ")
                    
     

#SECOND LEVEL IN GAME
def newmoonLvlTwo():
     print ("")
     print ("LEVEL TWO: NEW MOON")
     print ("")
     print ("You sit in a coffee shop, and take a sip of the latte in front of you")
     print ("'Disgusting...', you think.")
     print ("")
     time.sleep (5)
     print ("Below is a map of this level.")
     #MAP OF LEVEL
     print ("|‾‾‾‾‾‾‾‾‾|‾‾|‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾|")
     print ("|         |S |     _      _    |")
     print ("|‾‾‾‾‾‾‾| |T |    |_|    |_|   |")
     print ("|       | |R |       ALLEYS    |")
     print ("| CAFE  | |E | X   _      _    |")
     print ("|_______| |E |    |_|    |_|   |")
     print ("|         |T |                 |")
     print ("|_________|__|_________________|")
     time.sleep (10)
     print ("You notice a strange watch on the table in front of you.")
     time.sleep (3)
     print ("")
     print ("YOU GOT AN ITEM! >Time Travel Watch<")
     print ("Using this watch, you can travel to different places and times.")
     print ("       ,--.-----.--.")
     print ("       |--|-----|--|")
     print ("       |--|     |--|")
     print ("       |  |-----|  |")
     print ("     __|--|     |--|__")
     print ("    /  |  |-----|  |  \ ")
     print ("   /   \__|-----|__/   \ ")
     print ("  /   ______---______   \/\ ")
     print (" /   /               \   \/ ")
     print ("{   /    _     _   _  \   } ")
     print ("|  {    | | . | | | |  }  |-, ")
     print ("|  |    |_| . |_| |_|  |  | | ")
     print ("|  {                   }  |-' ")
     print ("{   \                 /   } ")
     print (" \   `------___------'   /\ ")
     print ("  \     __|-----|__     /\/ ")
     print ("   \   /  |-----|  \   / ")
     print ("    \  |--|     |--|  / ")
     print ("     --|  |-----|  |--")
     print ("       |--|     |--| ")
     print ("       |--|-----|--| ")
     print ("       `--'-----`--' ")

     print ("")
     time.sleep (5)
     ttwatch = ""
     while ttwatch not in options:
          ttwatch = input("Do you wear it on your wrist or hide it in your pocket? ")
          if ttwatch == "a":
               print ("")
               print ("It looks super cool and edgy, so you wear it on your wrist.")
               print ("Draining the rest of the disgusting latte, you almost choke.")
               print ("Spitting out what almost killed you, you realize that it is a small orange key!")
               time.sleep (8)
               print ("YOU GOT A KEY! 1/5")
               print ("")
               time.sleep (1)
               print ("That seemed easier than the >Piano Man< made it sound, hah.")
               time.sleep (1)
               print ("Starting down an empty street, you look up at the sky. A faint, thin sliver of an orange moon")
               print ("Is visible, barely showing among the many clouds. Suddenly, you get the feeling you are being watched.")
               print ("")
               time.sleep (6)
               print ("Turning around, you see a man in a suit wearing sunglasses, talking into a walkie talkie")
               print ("You hear him mutter 'time travel watch'. This can't be any good...")
               print ("")
               print ("Three more men dressed the same appear, and they start chasing you!!")
               print ("")
               time.sleep (6)
               print ("YOU HAVE ENCOUNTERED AN ENEMY >The Agents<")
               print ("")
               time.sleep (1)
               print ("After running for what seems like ages, you find shelter in a small alley.")
               print ("Looking down at the watch closer, you notice that it has a button on it, with rapidly")
               print ("increasing and decreasing numbers.")
               print ("")
               print ("Type 'yes' or 'no'.")
               buttonpress = ""
               while buttonpress not in yesorno:
                    buttonpress = input ("Do you press the button? ")
                    if buttonpress == "yes":
                         print ("")
                         print ("Just as you see >The Agents< spot you in the alley, you press the button on the watch.")
                         print ("")
                         print ("YOU HAVE ESCAPED >The Agents<! ENTERING LEVEL THREE SHORTLY:")
                         print ("")
                         time.sleep (5)
                         crescentLvlThree()
                    elif buttonpress == "no":
                         print ("")
                         print ("You're not gonna risk pressing a random button...")
                         print ("You hear shouting... oh no! >The Agents< have spotted you!")
                         print ("One of them grabs the watch from your wrist and another injects something into your neck.")
                         print ("")
                         time.sleep (7)
                         print ("The last thing you hear before you leave this world is")
                         print ('Thank goodness we got the watch before the orange moon was full...')
                         print ("")
                         print ("This is the end of you in our world and this one. Farewell.")
                         playgame_again()
                    else:
                         print ("")
                         print ("I didn't understand... can you repeat? ")
          elif ttwatch == "b":
               print ("")
               print ("It wouldn't be wise to show off such a dangerous looking watch.")
               print ("Draining the rest of the disgusting latte, you almost choke on an object in the cup.")
               print ("Spitting out what almost killed you, you realize that it is a small orange key!")
               time.sleep (6)
               print ("YOU GOT A KEY! 1/5")
               print ("")
               time.sleep (1)
               print ("Still slightly shook, you walk out of the cafe, just to see a man in a suit and ")
               print ("sunglasses walk by and mutter the word 'watch' into a walkie talkie.")
               print ("")
               print ("")
               curiosity = ""
               while curiosity not in options:
                    curiosity = input ("Do you follow him and see what he's up to or simply keep walking? ")
                    if curiosity == "a":
                         print ("")
                         print ("You decide to follow this man, since your curiosity gets the best of you.")
                         time.sleep (3)
                         print ("As you follow him, you suddenly see many more dressed like him gather around.")
                         print ("YOU HAVE ENCOUNTERED AN ENEMY >The Agents<")
                         print ("")
                         time.sleep (4)
                         print ("They mutter in low voices... and then one SPOTS YOU!")
                         time.sleep (5)
                         print ("They all turn around and start to chase you. Uh-oh.")
                         print ("")
                         print ("After running for what seems like ages, you find shelter in a small alley.")
                         print ("Looking down at the watch closer, you notice that it has a button on it, with rapidly")
                         print ("increasing and decreasing numbers.")
                         print ("")
                         print ("Type 'yes' or 'no'.")
                         buttonpress2 = ""
                         while buttonpress2 not in yesorno:
                              buttonpress2 = input ("Do you press the button? ")
                              if buttonpress2 == "yes":
                                   print ("")
                                   print ("Just as you see >The Agents< spot you in the alley, you press the button on the watch.")
                                   print ("")
                                   print ("YOU HAVE ESCAPED >The Agents<! ENTERING LEVEL THREE SHORTLY:")
                                   print ("")
                                   time.sleep (5)
                                   crescentLvlThree()
                              elif buttonpress2 == "no":
                                   print ("")
                                   print ("You're not gonna risk pressing a random button...")
                                   print ("You hear shouting... oh no! >The Agents< have spotted you!")
                                   print ("One of them grabs the watch from your wrist and another injects something into your neck.")
                                   print ("")
                                   time.sleep (7)
                                   print ("The last thing you hear before you leave this world is")
                                   print ('Thank goodness we got the watch before the orange moon was full...')
                                   print ("")
                                   print ("This is the end of you in our world and this one. Farewell.")
                                   playgame_again()
                              else:
                                   print ("")
                                   print ("I didn't understand... can you repeat?  ")
                    elif curiosity == "b":
                         print ("")
                         print ("You're not going to risk following this man... he could be dangerous, after all.")
                         print ("You look down at this watch carefully, and notice it has a button on it, with rapidly decreasing")
                         print ("and increasing numbers.")
                         buttonpress3 = ""
                         while buttonpress3 not in yesorno:
                              buttonpress3 = input ("Do you press the button? ")
                              if buttonpress3 == "yes":
                                   print ("")
                                   print ("you decide to press the button. Here goes nothing...")
                                   time.sleep (2)
                                   print ("YOU HAVE SUCCESSFULY COMPLETED LEVEL 2!")
                                   print ("ENTERING LEVEL THREE SHORTLY.")
                                   time.sleep (5)
                                   crescentLvlThree()
                              elif buttonpress2 == "no":
                                   print ("")
                                   print ("You're not gonna risk pressing a random button...")
                                   print ("You hear shouting... oh no! >The Agents< have spotted you!")
                                   print ("One of them grabs the watch from your wrist and another injects something into your neck.")
                                   print ("")
                                   time.sleep (7)
                                   print ("The last thing you hear before you leave this world is")
                                   print ('Thank goodness we got the watch before the orange moon was full...')
                                   print ("")
                                   print ("This is the end of you in our world and this one. Farewell.")
                                   playgame_again()
                              else:
                                   print ("")
                                   print ("I didn't understand... can you repeat?  ")
                    else:
                         print ("")
                         print ("What did you say? Can you please repeat? ")
          else:
               print ("")
               print ("I didn't understand... please repeat! ")

                    
#FIRST LEVEL IN GAME                        
def nomoonLvlOne():
     print ("")
     print ("As you approach the man playing the piano, he turns around slowly")
     print ("and stops playing.")
     print ("")
     time.sleep (5)
     print ("'Another lost traveler, I see? Worry not... well, I should introduce")
     print ("myself first, shouldn't I? I... am the >Piano Man<.")
     print ("")
     print ("YOU MADE AN ALLY! >Piano Man<")
     print ("")
     time.sleep (5)
     print ("Below is a map of this level.")
     print ("")
     print ("Take note; 'X' represents someone you will meet.")
     print ("")
     time.sleep (3)
     #MAP OF LEVEL
     print ("|‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾|")
     print ("|         _______             |")
     print ("|____     |chest|             |")
     print ("|    |    ‾‾‾‾‾‾‾          X  |")
     print ("|bar |    _       ‾      _____|")
     print ("|____|       tables     |piano|")
     print ("|            _           ‾‾‾‾‾|")
     print ("|_____________________________|")
     time.sleep (10)
     print ("'I'll explain how you can travel home... but first, what is your name?'")
     name = input("Insert your name, please. ")
     print ("")
     print ("'" + name + ", I see, excellent, excellent. Well, you are currently in level 1.")
     print ("You see that chest over there?' he points at a chest in the corner of the room,")
     print ("with five key holes. 'You must find five keys scattered in each level to unlock the '")
     print ("chest.")
     time.sleep (5)
     print ("")
     print ("In it, are the machine parts for you go get home. Each key represents one part.")
     print ("")
     print ("'You can also find items in each level, which may become useful in the future.'")
     print ("")
     time.sleep (3)
     print ("You may meet allies along the way... and beware of a very dangerous enemy...")
     print ("")
     print ("'You must be careful, since the Orange Moon will be full tonight. It causes this enemy")
     print ("to happen become stronger and much angrier...")
     print ("")
     print ("Type 'yes' or 'no'.")
     time.sleep (5)
     questAccept = ""
     while questAccept not in yesorno:
          questAccept = input ("Now the question is... do you accept the mission? ")
          if questAccept == "yes":
               print ("")
               print ("Great! One more thing; you cannot escape a level until you have gained ")
               print ("the key in it. So make sure you get each one!")
               print ("")
               time.sleep (4)
               print ("Handing you a backpack, he says, 'Put the stuff you find in here. Good luck!'")
               print ("")
               print ("Get ready, I'll send you to level two! THREE... TWO... ---")
               time.sleep (3)
               newmoonLvlTwo()
          elif questAccept == "no":
               print ("")
               print ("'That's ok! People reject quests all the time! I get that its scary. :)'")
               time.sleep (2)
               print ("The >Piano Man< hires you to work for him, and you happily spend")
               print ("the rest of your life wiping tables at the Piano Man Inn.")
               print ("")
               playgame_again()
          else:
               print ("")
               print ("'I didn't get that.' ")

#INTRODUCTION OF GAME
def gameIntro():
     print ("")
     print ("Enter any 'yes' or 'no' replies in lowercase")
     time.sleep (1)
     print ("")
     print ("If options are given, reply 'a' for the first option, and 'b' for the second, etc.")
     print ("")
     time.sleep (1)
     print ("YOU ARE NOW BEING SENT TO THE WORLD OF ORANGE MOON...")
     print ("")
     time.sleep (4)
     print ("3...")
     time.sleep (2)
     print ("2...")
     time.sleep (2)
     print ("1...")
     time.sleep (2)
     print ("")
     print ("LEVEL ONE: NO MOON")
     print ("")
     print ("You stand in a dingy looking inn. Around you, people sit at")
     print ("tables, with a cheery atmosphere in the air. But wait... why")
     print ("are you here? And how did you get in this place?")
     print ("")
     WhereAreYou = ""
     while WhereAreYou not in options:
          WhereAreYou = input("Do you ask the barista or the waitress? ")
          if WhereAreYou == "a":
               print ("")
               print ("You walk over to the barista, who stands, wiping glasses.")
               print ("'Can I help you?', she says. You explain to her that you ")
               print ("are quite lost, and don't know where you are.")
               time.sleep (5)
               print ("She rolls her eyes, and mutters 'Not another one.'")
               print ("'You see that man, playing the piano over there? Go talk to him.'")
               print ("How odd... You walk over to the man who plays the piano.")
               time.sleep (5)
               nomoonLvlOne()
          elif WhereAreYou == "b":
               print ("")
               print ("You head over to the waitress wiping tables. She looks up,")
               print ("and asks 'Can I help you?'. You stutter about how you are")
               print ("lost, and unsure of where you are. Rolling her eyes, she")
               print ("tells you to go to the man playing the piano across the room.")
               print ("Confused, you walk over to the piano player.")
               time.sleep (6)
               nomoonLvlOne()
          else:
               print ("")
               print ("I didn't understand that. ")

#This function starts the game.
gameIntro()

